### ISSUE TITLE
Integration with create-react-app?

### ISSUE THREAD

**Issue by stereobooster** [reasonml/rehydrate#81]
There is [integration with type-script](https://github.com/Microsoft/TypeScript-React-Starter). Any plans for something similar for Reason/Bucklescript?

UPD: [for ClojureScript](https://www.youtube.com/watch?v=BLDX5Twt2zk). See also [crra](https://github.com/knowbody/crra)

**Comment by marcusradell** [comment]
It was a while since I did this, but basic steps would be to first create the `cra` project, then install and setup the reason stuff with `bs-platform`.

Then modify the build command to first build `.re` files to `.js` files followed by the `cra` build script.

For watch mode, you run them both in parallel, so bs-platform watches source files, builds to javascript, and when that happens, webpack will pick up the change and build the `cra` output.

(I'd wish I could help write something up, but it's hard for me to take time to keep up with Reason until I can actually use it full time in my hobby project. But I'm missing rxjs replacement, and too bad at the type system to write it.)

**Comment by stereobooster** [comment]
Thanks, kind of what they doing for [sass support](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-a-css-preprocessor-sass-less-etc).

**Comment by bbohen** [comment]
@stereobooster you might want to check out [crra](https://github.com/knowbody/crra), it has support for bucklescript and the reason-react bindings.

**Comment by stereobooster** [comment]
https://github.com/reasonml-community/reason-scripts is what I looked for
